{{- range $volume, $spec := .Values.volumes }}
{{- $name := printf "%s-%s" $spec.namespace $volume }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $name }}
  {{- if $spec.annotations }}
  annotations: {{- toYaml $spec.annotations | nindent 4 }}
  {{- end }}
  {{- if $spec.labels }}
  labels:  {{- toYaml $spec.labels | nindent 4 }}
  {{- end }}
spec:
  capacity:
    storage: {{ $spec.capacity | quote }}
  volumeMode: {{ $spec.volumeMode | default "Filesystem" }}
  accessModes:
    - {{ $spec.accessMode }}
  persistentVolumeReclaimPolicy: {{ $spec.reclaimPolicy | default "Retain" }}
  storageClassName: {{ $spec.storageClass | default "" | quote }}
  {{- if $spec.csi }}
  csi:
  {{ toYaml $spec.csi | indent 2 }}
  {{- end }}
  {{- if $spec.nfs }}
  nfs:
    server: {{ $spec.nfs.server }}
    path: {{ $spec.nfs.path }}
  {{- if $spec.nfs.mountOptions }}
  mountOptions:
    {{- range $spec.nfs.mountOptions }}
    - {{ . }}
    {{- end }}
  {{- end }}
  {{- end }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ $volume }}
  {{- if $spec.annotations }}
  annotations: {{- toYaml $spec.annotations | nindent 4 }}
  {{- end }}
  {{- if $spec.labels }}
  labels:  {{- toYaml $spec.labels | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ $spec.accessMode | quote }}
  resources:
    requests:
      storage: {{ $spec.capacity | quote }}
  storageClassName: {{ $spec.storageClass | default "" | quote }}
{{- end }}