{{- range .Values.volumes }}
{{- $parsedName := printf "%s-%s" .namespace .name }}
{{- $name := .pvName | default $parsedName | lower }}
{{ $accessMode := .accessMode | default "ReadWriteOnce" }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $name }}
  {{- if .annotations }}
  annotations: {{- toYaml .annotations | nindent 4 }}
  {{- end }}
  labels:
    fcd-id: {{ .volumeHandle }}
    name: {{ $name }}
    namespace: {{ .namespace }}
    {{- if .pvName }}
    pv-name: {{ .pvName }}
    {{- end }}
    {{- if .vmdkPath }}
    vmdk-path: {{ .vmdkPath }}
    {{- end }}
    {{- if .datastore }}
    datastore: {{ .datastore }}
    {{- end }}
spec:
  capacity:
    storage: {{ .capacity | quote }}
  volumeMode: {{ .volumeMode | default "Filesystem" }}
  accessModes: [{{ $accessMode | quote }}]
  persistentVolumeReclaimPolicy: {{ .reclaimPolicy | default "Retain" }}
  storageClassName: {{ .storageClass | default "" | quote }}
  claimRef:
    apiVersion: {{ .apiVersion | default "v1" }}
    kind: {{ .kind | default "PersistentVolumeClaim" }}
    name: {{ .name }}
    namespace: {{ .namespace }}
  csi:
    driver: {{ .driver | default "csi.vsphere.vmware.com" }}
    fsType: {{ .fsType | default "ext4" }}
    volumeAttributes:
      type: {{ .type | default "vSphere CNS Block Volume" }}
    volumeHandle: {{ .volumeHandle }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .name }}
  {{- if .annotations }}
  annotations: {{- toYaml .annotations | nindent 4 }}
  {{- end }}
  {{- if .labels }}
  labels:  {{- toYaml .labels | nindent 4 }}
  {{- end }}
spec:
  accessModes: [{{ $accessMode | quote }}]
  resources:
    requests:
      storage: {{ .capacity | quote }}
  selector:
    matchLabels:
      fcd-id: {{ .volumeHandle }}
      name: {{ $name }}
      namespace: {{ .namespace }}
      {{- if .pvName }}
      pv-name: {{ .pvName }}
      {{- end }}
      {{- if .vmdkPath }}
      vmdk-path: {{ .vmdkPath }}
      {{- end }}
      {{- if .datastore }}
      datastore: {{ .datastore }}
      {{- end }}
  storageClassName: {{ .storageClass | default "" | quote }}
  volumeMode: {{ .volumeMode | default "Filesystem" | quote }}
  volumeName: {{ $name }}
{{- end }}