{{- $strategy := default "Recreate" .Values.strategy }}
{{- $service := .Values.service }}
apiVersion: apps/v1
kind: Deployment
metadata:
  {{- with (merge (.Values.annotations | default dict) (include "qbittorrent-vpn.annotations" $ | fromYaml)) }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "qbittorrent-vpn.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "qbittorrent-vpn.labels" . | nindent 4 }}
spec:
  progressDeadlineSeconds: {{ .Values.progressDeadlineSeconds | default 600 }}
  replicas: {{ .Values.replicas | default 1 }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit | default 3 }}
  selector:
    matchLabels:
      {{- include "qbittorrent-vpn.selectorLabels" . | nindent 6 }}
  strategy:
    type: {{ $strategy }}
    {{- with .Values.rollingUpdate }}
      {{- if and (eq $strategy "RollingUpdate") (or .surge .unavailable) }}
    rollingUpdate:
        {{- with .unavailable }}
      maxUnavailable: {{ . }}
        {{- end }}
        {{- with .surge }}
      maxSurge: {{ . }}
        {{- end }}
      {{- end }}
    {{- end }}
  template:
    metadata:
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      labels:
        {{- include "qbittorrent-vpn.selectorLabels" . | nindent 8 }}
    spec:
      automountServiceAccountToken: {{ .Values.automountServiceAccountToken | default true }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      serviceAccountName: {{ include "qbittorrent-vpn.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.args }}
          args:
            {{- if kindIs "string" . }}
            - {{ . }}
            {{- else }}
            {{ toYaml . | nindent 4 }}
            {{- end }}
          {{- end }}
          {{- with .Values.command }}
          command:
            {{- if kindIs "string" . }}
            - {{ . }}
            {{- else }}
              {{ toYaml . | nindent 4 }}
            {{- end }}
          {{- end }}
          env:
            {{- toYaml .Values.env | nindent 12 }}
          envFrom:
            {{- toYaml .Values.envFrom | nindent 12 }}
          image: {{ printf "%s:%s" .Values.image.repository (default "latest" .Values.image.tag) | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy | default "IfNotPresent" }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          ports:
            - containerPort: {{ $service.httpPort | default 8080 }}
              name: {{ $service.name | default "http" }}
              protocol: {{ $service.protocol | default "TCP" }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          terminationMessagePath: {{ .Values.termination.messagePath }}
          terminationMessagePolicy: {{ .Values.termination.messagePolicy }}
          volumeMounts:
            {{- toYaml .Values.volumeMounts | nindent 12 }}
        - name: {{ .Values.vpn.name }}
          env:
            {{- toYaml .Values.vpn.env | nindent 12 }}
          envFrom:
            {{- toYaml .Values.vpn.envFrom | nindent 12 }}
          image: "{{ .Values.vpn.image.repository }}:{{ .Values.vpn.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.vpn.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.vpn.securityContext | nindent 12 }}
          terminationMessagePath: {{ .Values.termination.messagePath }}
          terminationMessagePolicy: {{ .Values.termination.messagePolicy }}
          volumeMounts:
            {{- toYaml .Values.vpn.volumeMounts | nindent 12 }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      enableServiceLinks: {{ .Values.enableServiceLinks | default true }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      serviceAccount: {{ include "qbittorrent-vpn.serviceAccountName" . }}
      serviceAccountName: {{ include "qbittorrent-vpn.serviceAccountName" . }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds | default 30 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
