apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |
    tagging:
        drop:
            {{- range .Values.tagging.drop }}
            - {{ . }}
            {{- end }}
        replacements:
            {{- range $key, $val := .Values.tagging.replacements }}
            {{ $key }}: {{ $val }}
            {{- end}}
