# Default values for plex-linker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: jb6magic/plex_linker
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: latest
secret:
  PLEX_API_KEY: ""
  PLEX_PASSWORD: ""
  PLEX_SERVER: ""
  PLEX_USERNAME: ""
  RADARR_API_KEY: ""
  SONARR_API_KEY: ""

configmap:
  config:
    enabled: true
    data:
      APPEND_TO_CRON_END: ""
      CONFIG_ARCHIVES: /config/config_files/archives
      DOCKER_MEDIA_PATH: /media/video
      FREQUENCY: 1
      GIT_BRANCH: master
      GIT_REPO: https://github.com/jd4883/plex-linker-beta.git
      HOST_MEDIA_PATH: /media/video
      LOGS: /config/logs
      LOG_NAME: plex-linker
      PLEX_ANIME: Anime
      PLEX_LINKER: /config
      PLEX_MOVIES: Movies
      PLEX_SHOWS: TV Shows
      PLEX_URL: http://plex.plex:32400
      RADARR_DEFAULT_ROOT: movies
      RADARR_ROOT_PATH_PREFIX: /
      RADARR_URL: http://radarr.radarr:7878/api
      SEASON_INT: 0
      SEASON_STR: "00"
      SONARR_DEFAULT_ROOT: tv
      SONARR_ROOT_PATH_PREFIX: /data/
      SONARR_URL: http://sonarr.sonarr:8989/api
      YAML_FILE_CURRENT: /config/config_files/media_collection_parsed_this_run.yaml
      YAML_FILE_PREVIOUS: /config/config_files/media_collection_parsed_last_run.yaml

envFrom:
  - secretRef:
      name: PLEX_API_KEY
  - secretRef:
      name: PLEX_PASSWORD
  - secretRef:
      name: PLEX_SERVER
  - secretRef:
      name: PLEX_USERNAME
  - secretRef:
      name: RADARR_API_KEY
  - secretRef:
      name: SONARR_API_KEY
  - configMapRef:
      name: config

persistence:
  config:
    enabled: false
    mountPath: /config
  media:
    enabled: false
    mountPath: /media

service: {}
