{{- if .Values.operator.create }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.operator.applicationName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: operator
    {{- include "onepassword-connect.labels" . | nindent 4 }}
  {{- with .Values.operator.labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.operator.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ .Values.connect.applicationName }}
  template:
    metadata:
      labels:
        name: {{ .Values.connect.applicationName }}
        app.kubernetes.io/component: operator
      {{- with .Values.operator.podLabels }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.operator.podAnnotations }}
      annotations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- if .Values.connect.nodeSelector }}
      nodeSelector: {{ toYaml .Values.operator.nodeSelector | nindent 8 }}
      {{- end }}
      dnsConfig:
        nameservers: {{- toYaml .Values.dnsConfig.nameservers | nindent 10 }}
        {{- if .Values.dnsConfig.searches }}
        searches: {{- toYaml .Values.dnsConfig.searches | nindent 10 }}
        {{- end }}
      dnsPolicy: {{ .Values.dnsPolicy | quote }}
      tolerations:
        {{ toYaml .Values.operator.tolerations }}
      serviceAccountName: {{ .Values.operator.serviceAccount.name }}
      containers:
        - name: {{ .Values.connect.applicationName }}
          image: {{ .Values.operator.imageRepository }}:{{ .Values.operator.version | default "latest" }}
          imagePullPolicy: {{ .Values.connect.imagePullPolicy }}
          securityContext:
            {{- toYaml .Values.operator.securityContext | nindent 12 }}
          command: ["/manager"]
          args: [--zap-log-level={{ .Values.operator.logLevel }}]
          env:
            - name: WATCH_NAMESPACE
              value: {{ default "" (tpl (include "helm-toolkit.utils.joinListWithComma" .Values.operator.watchNamespace) .) }}
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "{{ .Values.operator.applicationName }}"
            - name: OP_CONNECT_HOST
              value: "{{- include "onepassword-connect.url" . }}"
            - name: POLLING_INTERVAL
              value: "{{ .Values.operator.pollingInterval }}"
            - name: OP_CONNECT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.operator.token.name }}
                  key: {{ .Values.operator.token.key }}
            - name: AUTO_RESTART
              value: "{{ .Values.operator.autoRestart }}"
            {{- range .Values.operator.customEnvVars}}
            - name: {{ .name }}
              value: {{ .value }}
            {{- end }} 
          resources:
            {{- toYaml .Values.operator.resources | nindent 12 }}
{{- end }}
